// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/refresh.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/test-token': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/test-token.post').default>>>>
    }
    '/api/example/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/example/create.post').default>>>>
    }
    '/api/example/demo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/example/demo.get').default>>>>
    }
    '/api/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects.get').default>>>>
    }
    '/api/projects/:id/rename': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/rename.patch').default>>>>
    }
    '/api/projects/create-simple': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/create-simple.post').default>>>>
    }
    '/api/projects/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/create.post').default>>>>
    }
    '/api/projects/debug': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/debug.post').default>>>>
    }
    '/api/projects/test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/test.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}